import { TaskObject } from './models/task.model';
import { UserObject } from './models/user.model';

export const USERS: UserObject[] = [
  {
    id: 'u1',
    name: 'Jasmine Washington',
    avatar: 'user-1.jpg',
  },
  {
    id: 'u2',
    name: 'Emily Thompson',
    avatar: 'user-2.jpg',
  },
  {
    id: 'u3',
    name: 'Marcus Johnson',
    avatar: 'user-3.jpg',
  },
  {
    id: 'u4',
    name: 'David Miller',
    avatar: 'user-4.jpg',
  },
  {
    id: 'u5',
    name: 'Priya Patel',
    avatar: 'user-5.jpg',
  },
  {
    id: 'u6',
    name: 'Arjun Singh',
    avatar: 'user-6.jpg',
  },
];

export const TASKS: TaskObject[] = [
  {
    id: 't1',
    userId: 'u1',
    title: 'Master Angular',
    summary: 'Learn all the basic and advanced features of Angular & how to apply them.',
    dueDate: '2025-12-31',
  },
  {
    id: 't2',
    userId: 'u3',
    title: 'Build first prototype',
    summary: 'Build a first prototype of the online shop website',
    dueDate: '2024-05-31',
  },
  {
    id: 't3',
    userId: 'u3',
    title: 'Prepare issue template',
    summary: 'Prepare and describe an issue template which will help with project management',
    dueDate: '2024-06-15',
  },
  {
    id: 't5',
    userId: 'u1',
    title: 'Build a portfolio app',
    summary: 'Create a personal portfolio using Angular components and routing.',
    dueDate: '2025-06-15',
  },
  {
    id: 't6',
    userId: 'u1',
    title: 'Learn Signals deeply',
    summary: 'Understand signals, computed, and effects in Angular.',
    dueDate: '2025-07-01',
  },
  {
    id: 't7',
    userId: 'u1',
    title: 'Practice RxJS basics',
    summary: 'Learn observables, operators, and subscriptions.',
    dueDate: '2025-08-10',
  },
  {
    id: 't8',
    userId: 'u1',
    title: 'Build a small dashboard',
    summary: 'Combine components, services, and state management.',
    dueDate: '2025-09-01',
  },
  {
    id: 't9',
    userId: 'u2',
    title: 'Learn TypeScript fundamentals',
    summary: 'Understand types, interfaces, and generics.',
    dueDate: '2025-05-01',
  },
  {
    id: 't10',
    userId: 'u2',
    title: 'Build a to-do app',
    summary: 'Create a simple task manager using Angular.',
    dueDate: '2025-06-20',
  },
  {
    id: 't11',
    userId: 'u2',
    title: 'Study Angular routing',
    summary: 'Learn navigation, params, and lazy loading.',
    dueDate: '2025-07-10',
  },
  {
    id: 't12',
    userId: 'u2',
    title: 'CSS practice',
    summary: 'Improve layout skills using Flexbox and Grid.',
    dueDate: '2025-04-30',
  },
  {
    id: 't13',
    userId: 'u2',
    title: 'Deploy first app',
    summary: 'Deploy Angular app to a hosting platform.',
    dueDate: '2025-08-01',
  },
  {
    id: 't14',
    userId: 'u3',
    title: 'Add authentication',
    summary: 'Implement login and signup functionality.',
    dueDate: '2024-07-20',
  },
  {
    id: 't15',
    userId: 'u3',
    title: 'Improve UI design',
    summary: 'Enhance styling and user experience.',
    dueDate: '2024-08-05',
  },
  {
    id: 't16',
    userId: 'u4',
    title: 'Learn Angular basics',
    summary: 'Understand components, templates, and directives.',
    dueDate: '2025-03-10',
  },
  {
    id: 't17',
    userId: 'u4',
    title: 'Practice forms',
    summary: 'Work with template-driven and reactive forms.',
    dueDate: '2025-04-01',
  },
  {
    id: 't18',
    userId: 'u1',
    title: 'HTTP requests',
    summary: 'Learn how to fetch data from APIs.',
    dueDate: '2025-05-15',
  },
  {
    id: 't19',
    userId: 'u1',
    title: 'State management intro',
    summary: 'Understand basic state handling patterns.',
    dueDate: '2025-06-10',
  },
  {
    id: 't20',
    userId: 'u4',
    title: 'Mini blog app',
    summary: 'Build a simple blog with posts and comments.',
    dueDate: '2025-07-25',
  },
  {
    id: 't26',
    userId: 'u6',
    title: 'Learn Angular CLI',
    summary: 'Understand project generation and build tools.',
    dueDate: '2025-03-05',
  },
  {
    id: 't27',
    userId: 'u6',
    title: 'Practice components',
    summary: 'Create reusable UI components.',
    dueDate: '2025-04-10',
  },
  {
    id: 't28',
    userId: 'u6',
    title: 'Signals introduction',
    summary: 'Learn reactive state with signals.',
    dueDate: '2025-05-05',
  },
  {
    id: 't29',
    userId: 'u6',
    title: 'Build weather app',
    summary: 'Fetch weather data from an API.',
    dueDate: '2025-06-15',
  },
];
